In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df=pd.read_csv("/content/Car_sales.csv")
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [ ]:
table=pd.pivot_table(df,values="Sales_in_thousands",index="Vehicle_type",columns="Model",aggfunc=np.sum)
table

<ipython-input-6-01957cd45616>:1: FutureWarning: The provided callable <function sum at 0x7e0d12312dd0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  table=pd.pivot_table(df,values="Sales_in_thousands",index="Vehicle_type",columns="Model",aggfunc=np.sum)

Model,3-Sep,3000GT,300M,323i,328i,4Runner,5-Sep,528i,A4,A6,...,Town & Country,Town car,V40,V70,Villager,Viper,Voyager,Windstar,Wrangler,Xterra
Vehicle_type,,,,,,,,,,,,,,,,,,,,,
Car,NaN,NaN,NaN,NaN,NaN,68.411,NaN,NaN,NaN,NaN,...,53.48,NaN,NaN,NaN,20.38,NaN,24.155,155.787,55.557,54.158
Passenger,12.115,0.11,30.696,19.747,9.231,NaN,9.191,17.527,20.397,18.78,...,NaN,48.911,3.545,17.531,NaN,0.916,NaN,NaN,NaN,NaN

In [ ]:
table=pd.pivot_table(df,values="Price_in_thousands",index="Manufacturer",columns="Model",aggfunc=np.mean)
table

<ipython-input-7-2668222c4fc6>:1: FutureWarning: The provided callable <function mean at 0x7e0d12313d00> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  table=pd.pivot_table(df,values="Price_in_thousands",index="Manufacturer",columns="Model",aggfunc=np.mean)

Model,3-Sep,3000GT,300M,323i,328i,4Runner,5-Sep,528i,A4,A6,...,Taurus,Town car,V40,V70,Villager,Viper,Voyager,Windstar,Wrangler,Xterra
Manufacturer,,,,,,,,,,,,,,,,,,,,,
Acura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Audi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.99,33.95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BMW,NaN,NaN,NaN,26.99,33.4,NaN,NaN,38.9,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Buick,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cadillac,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Chevrolet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Chrysler,NaN,NaN,29.185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dodge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,69.725,NaN,NaN,NaN,NaN
Ford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.885,NaN,NaN,NaN,NaN,NaN,NaN,21.41,NaN,NaN
Honda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hyundai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Infiniti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jaguar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jeep,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.46,NaN
Lexus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lincoln,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,43.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mercedes-B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mercury,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,22.51,NaN,NaN,NaN,NaN,NaN
Mitsubishi,NaN,25.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nissan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.799
Oldsmobile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Plymouth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18.85,NaN,NaN,NaN
Pontiac,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Porsche,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Saab,26.1,NaN,NaN,NaN,NaN,NaN,33.12,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Saturn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Subaru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Toyota,NaN,NaN,NaN,NaN,NaN,22.288,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Volkswagen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Volvo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,24.4,28.8,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
table=pd.pivot_table(df,values="Price_in_thousands",index="Vehicle_type",columns="Model",aggfunc=np.mean)
table

<ipython-input-10-b650f91b5b14>:1: FutureWarning: The provided callable <function mean at 0x7e0d12313d00> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  table=pd.pivot_table(df,values="Price_in_thousands",index="Vehicle_type",columns="Model",aggfunc=np.mean)

Model,3-Sep,3000GT,300M,323i,328i,4Runner,5-Sep,528i,A4,A6,...,Taurus,Town car,V40,V70,Villager,Viper,Voyager,Windstar,Wrangler,Xterra
Vehicle_type,,,,,,,,,,,,,,,,,,,,,
Car,NaN,NaN,NaN,NaN,NaN,22.288,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,22.51,NaN,18.85,21.41,14.46,22.799
Passenger,26.1,25.45,29.185,26.99,33.4,NaN,33.12,38.9,23.99,33.95,...,17.885,43.33,24.4,28.8,NaN,69.725,NaN,NaN,NaN,NaN

In [ ]:
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [ ]:
table=pd.pivot_table(df,values="Sales_in_thousands",index="Vehicle_type",columns="Model",aggfunc=np.mean)
table

<ipython-input-17-89a47c25b853>:1: FutureWarning: The provided callable <function mean at 0x7e0d12313d00> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  table=pd.pivot_table(df,values="Sales_in_thousands",index="Vehicle_type",columns="Model",aggfunc=np.mean)

Model,3-Sep,3000GT,300M,323i,328i,4Runner,5-Sep,528i,A4,A6,...,Town & Country,Town car,V40,V70,Villager,Viper,Voyager,Windstar,Wrangler,Xterra
Vehicle_type,,,,,,,,,,,,,,,,,,,,,
Car,NaN,NaN,NaN,NaN,NaN,68.411,NaN,NaN,NaN,NaN,...,53.48,NaN,NaN,NaN,20.38,NaN,24.155,155.787,55.557,54.158
Passenger,12.115,0.11,30.696,19.747,9.231,NaN,9.191,17.527,20.397,18.78,...,NaN,48.911,3.545,17.531,NaN,0.916,NaN,NaN,NaN,NaN

In [19]:
table=pd.pivot_table(df,values=["Sales_in_thousands","Price_in_thousands"],index="Vehicle_type",columns=["Manufacturer","Horsepower"],aggfunc=[np.sum,np.mean])
table

<ipython-input-19-972e9a2784f7>:1: FutureWarning: The provided callable <function sum at 0x7e0d12312dd0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  table=pd.pivot_table(df,values=["Sales_in_thousands","Price_in_thousands"],index="Vehicle_type",columns=["Manufacturer","Horsepower"],aggfunc=[np.sum,np.mean])
<ipython-input-19-972e9a2784f7>:1: FutureWarning: The provided callable <function mean at 0x7e0d12313d00> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  table=pd.pivot_table(df,values=["Sales_in_thousands","Price_in_thousands"],index="Vehicle_type",columns=["Manufacturer","Horsepower"],aggfunc=[np.sum,np.mean])

                            sum                                               \
             Price_in_thousands
Manufacturer              Acura               Audi                 BMW
Horsepower                140.0 210.0 225.0  150.0  200.0 310.0  170.0 193.0
Vehicle_type
Car                         NaN   NaN   NaN    NaN    NaN   NaN    NaN   NaN
Passenger                  21.5  42.0  28.4  23.99  33.95  62.0  26.99  72.3

                             ...               mean                         \
                             ... Sales_in_thousands
Manufacturer   Buick         ...             Toyota
Horsepower     175.0  205.0  ...              150.0   194.0   210.0  230.0
Vehicle_type                 ...
Car              NaN    NaN  ...             68.411  65.119     NaN  9.835
Passenger     21.975  59.85  ...                NaN     NaN  63.849    NaN



Manufacturer Volkswagen           Volvo
Horsepower        115.0   150.0   160.0   168.0   201.0  236.0
Vehicle_type
Car                 NaN     NaN     NaN     NaN     NaN    NaN
Passenger        31.622  51.102  10.251  16.388  18.969  3.493

[2 rows x 512 columns]